### ISSUE TITLE
42coin doesnt work.

### ISSUE THREAD

**Issue by 0xicl33n** [mrsmn/coinmarketcap-api#1]
import coinmarketcap as cmc

    FOURTYTWO_PRICE = cmc.price('42')
    print FOURTYTWO_PRICE

Traceback (most recent call last):
  File "coinsnake.py", line 23, in <module>
    FOURTYTWO_PRICE = cmc.price('42')
  File "C:\Python27\lib\site-packages\coinmarketcap\coinmarketcap_api.py", line 39, in price
    return coin_info(PARAMETER)[4]
IndexError: list index out of range

http://coinmarketcap.com/currencies/42-coin/

**Comment by mrsmn** [comment]
Hi there,

thank you for reporting this. Unfortunately I'm nowhere near a computer right now
so I'll have a look at this tomorrow.

Cheers.

**Comment by mrsmn** [comment]
Well then, that was an easy fix. Don't worry about it, glad you managed to get it working.
