### ISSUE TITLE
KeyError on 4.0 not in 3.0.1

### ISSUE THREAD

**Issue by Aro2220** [mrsmn/coinmarketcap-api#18]
Getting this error with version 4.0. Did not have any trouble with 3.0.1. 
With 4.0 it says I need requests_cache. When I install requests_cache I get this error:
`
>>> import coinmarketcap
>>> coinmarketcap = coinmarketcap.Market()
>>> stats = coinmarketcap.stats()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/coinmarketcap/core.py", line 64, in stats
    response = self.__request('global/', params)
  File "/usr/local/lib/python2.7/dist-packages/coinmarketcap/core.py", line 34, in __request
    response[0][u'cached'] = response_object.from_cache
KeyError: 0
`

**Comment by mrsmn** [comment]
Hi there,

thanks for reporting the issue, this is indeed a bug. I'll look into it tomorrow as it's getting a bit late.

Cheers.

**Comment by mrsmn** [comment]
I've pushed v.4.0.1 which fixes your issue. I've had to remove ```response_object.from_cache``` for now as the implementation I have works on a list of dicts but not on a dict. I'll try and figure this out in the next couple of days and I'll publish v.4.0.2.

Thanks again for reporting this.

Cheers.

**Comment by mrsmn** [comment]
@Aro2220 v.4.1 is out, I've fixed the ```response_object.from_cache``` issue. Could you try it out and see if it works as intended?

Cheers.

**Comment by Aro2220** [comment]
Hi again, I've updated to the latest Coinmarketcap and tested it. The program is running along fine. Thanks for everything :)
