### ISSUE TITLE
Python3 support?

### ISSUE THREAD

**Issue by Jzarecta** [mrsmn/coinmarketcap-api#2]
Wonder if this module has Python3 support and what to do to adjust.
Tried getting it in my python3 pip but got the issue of:
```
read(README)...
```
Instead I used open(README)... and worked. However the new issue is that when it tries to import the coinmarketcap_api and fails. 
```
  File "/usr/local/lib/python3.4/dist-packages/coinmarketcap/__init__.py", line 19, in <module>
    from coinmarketcap_api import (
ImportError: No module named 'coinmarketcap_api'
```

**Comment by mrsmn** [comment]
Hi there,

thank you for reporting this. I'll try to fix this as soon as I find some spare time.
PR's are welcome though :stuck_out_tongue:

Cheers.

**Comment by mrsmn** [comment]
@Jzarecta I've found the issue, I'm preparing a fix that'll work for both Python 2 and 3.
Should push it sometime this week.

Cheers.

**Comment by Jzarecta** [comment]
Cool, can't wait to get the update to make my script work. Looking to get a table of the altcoin valuation of selected altcoins.

**Comment by Jzarecta** [comment]
Any update on this?

**Comment by mrsmn** [comment]
@Jzarecta I've been quite busy the last few weeks but I'll try to cook something up. I basically know what the issues are, I just need an elegant way of fixing them.

Cheers.

**Comment by Jzarecta** [comment]
From the #python chatroom they told me the best practice for backward compatiblity is using the 'six module': 'Six provides simple utilities for wrapping over differences between Python 2 and Python 3. It is intended to support codebases that work on both Python 2 and 3 without modification. six consists of only one Python file, so it is painless to copy into a project.'

https://pythonhosted.org/six/

**Comment by mrsmn** [comment]
@Jzarecta I've just pushed to ```@development```, I haven't tested the code though. Could you give it a spin under Python 3.x and tell me how it works?

Thank you.

**Comment by mrsmn** [comment]
@Jzarecta fixed on ```@master``` and pushed to PyPI :smile:
