### ISSUE TITLE
ModuleNotFoundError: No module named 'requests_cache'

### ISSUE THREAD

**Issue by clu8** [mrsmn/coinmarketcap-api#20]
I'm getting `ModuleNotFoundError: No module named 'requests_cache'` when trying to `import coinmarketcap` after a clean install from pip. Maybe `requests-cache` needs to be added to the dependencies?

**Comment by mrsmn** [comment]
Hi there,
```requests-cache``` is in the [list of required dependencies.](https://github.com/mrsmn/coinmarketcap-api/blob/master/requirements.txt)
Please use
```pip install -r requirements.txt```to install them.

Cheers.

**Comment by mrsmn** [comment]
This was partially my bad: I've since added ```requests-cache```to the list of dependencies in the ```setup.py```file. See #19 .
