### ISSUE TITLE
Get price on bitcoin

### ISSUE THREAD

**Issue by Jzarecta** [mrsmn/coinmarketcap-api#3]
Anyway I can get the altcoin prices on Bitcoins?

**Comment by mrsmn** [comment]
I don't really understand your question. What do you want to do exactly?

Cheers.

**Comment by Jzarecta** [comment]
```python
>>> coinmarketcap.price_btc('nxt')
Ƀ 0.00001616
```

**Comment by mrsmn** [comment]
Oh, I understand. As that's not really a part of the coinmarketcap "API" I won't implement it into this project but it should be pretty staightforward to write code doing that with the data provided by this library.

Cheers.

**Comment by mrsmn** [comment]
Will not be implemented in the module as it can be done externally in a few lines of code.
