### ISSUE TITLE
Strange error 

### ISSUE THREAD

**Issue by SheffieldCrypto** [mrsmn/coinmarketcap-api#6]
I just installed via pip on windows, importing 'coinmarketcap' brings this error: 

Traceback (most recent call last):
  File "C:\Users\David\Desktop\Python\JSON\UTC_test.py", line 1, in <module>
    import coinmarketcap
  File "C:\Python27\lib\site-packages\coinmarketcap\__init__.py", line 19, in <module>
    from .core import (
ImportError: cannot import name about
[Finished in 0.4s with exit code 1]

Any ideas ?

**Comment by mrsmn** [comment]
Hi there,

this is fixed by the latest commit to master, was introduced when I removed the coinmarketcap.about() call. Thank you for reporting this.

Cheers.

**Comment by SheffieldCrypto** [comment]
Thank you for your shift reply sir, Merry Christmas !
