### ISSUE TITLE
Some coins don't work 

### ISSUE THREAD

**Issue by SheffieldCrypto** [mrsmn/coinmarketcap-api#7]
Hey again, 

I'm wondering if you can help me, i'm trying to pull volume for each coin. 
Out of 120 coins 15 don't work, i suspect it's because the coin names I have are different here's the pastebin for the coins that don't work:  (i included DOGE as a control) 
http://pastebin.com/uqawGyqw

I got the coin names from a scrapper on poloniex, so maybe some of them don't match, is there a way to use the coin symbol to acquire the coin name so i can replace all my existing coin names with the correct ones that agree with coinmarketcap's ?

Here's a copy of the spreadsheet im saving the data to: 
[new_values2.xlsx](https://github.com/mrsmn/coinmarketcap-api/files/71682/new_values2.xlsx)

Tremendous Thanks 

Dave

**Comment by mrsmn** [comment]
Hi there,

some currency names on ```coinmarketcap``` indeed won't match with ones from ```Poloniex```.
I bascially get the coin name with the following:

```python
raw_data.xpath('//tr[@id="id-' + PARAMETER + '"]/td//text()')
```
which will match the following:

```
<tr id="id-bitcoin" class="">
```

You could implement some additional function (say ```.all()``) the would return you a list of all the coins.
If that's too much trouble, just have a look at the ```coinmarketcap``` source code and search for the table row containing the desired coin, you'll get the ID that way.

Hope this helps.

Cheers.

**Comment by SheffieldCrypto** [comment]
Hey, thanks for the reply. 

I'm a little confused, as when i use the coin name as it appears on coinmarketcap (removing all spaces and caps) it still throws an error. 

I'm not familiar with raw_data.xpath('//tr[@id="id-' + PARAMETER + '"]/td//text()') is this HTML ? I'm a beginner python program. 

Any advice ?

Thanks,

**Comment by SheffieldCrypto** [comment]
Also is it possible to get volume for each coin from individual exchanges? i'm interested in ones on poloniex http://coinmarketcap.com/exchanges/poloniex/

**Comment by mrsmn** [comment]
Hi,

you can get the coin ID like this:

<img width="1920" alt="capture d ecran 2015-12-26 a 16 51 59" src="https://cloud.githubusercontent.com/assets/2029239/12007026/281bd60c-abf1-11e5-86d4-2e378ed31ee2.png">

The exchange calls haven't been implement into this module yet but I might be able to look into it after the Holiday break. I'll gladly accept any PRs :stuck_out_tongue: 

Cheers.
