### ISSUE TITLE
Trying to scrape all data 

### ISSUE THREAD

**Issue by loba333** [mrsmn/coinmarketcap-api#8]
Hi there, 

I'm trying to scrape, on a daily basis, the summary for each coin using this function:
coinmarketcap.coin_summary('bitcoin')

However i'm struggling to find a way to get all the coin names. Do you happen to have a list ? 

Kind Regards,

**Comment by mrsmn** [comment]
Hi,

I don't have a list of all the coins but you could come up with a way to get all coin IDs in a couple of LOC.
[Have a look at this](https://github.com/mrsmn/coinmarketcap-api/issues/7#issuecomment-167338016) for a way to get a coin ID

**Comment by loba333** [comment]
Hey, thanks for the reply. 

Hm I can only code basic programs in python, could you kindly give further instructions on what code i would need to write in scrape the ID in each element for each coin ? 

Regards

**Comment by mrsmn** [comment]
Hi,

you will indeed need to scrape the coinmarketcap HTML. You coul adapt the ```coin_info()```function in [coinmarketcap/utils.py](https://github.com/mrsmn/coinmarketcap-api/blob/master/coinmarketcap%2Futils.py#L16) to suit your needs.

Cheers.

**Comment by loba333** [comment]
I have scrapped the HTML and have a csv of coins and their codes, would you like me to send it and the code over to you encase someone requires it ? ..... just a thought

**Comment by mrsmn** [comment]
Hi there,

you could always create a PR an add the CSV file to the ```doc```directory. :smile: 
I'm closing this as you've resolved the issue.

Much appreciated.

Cheers.
